### ISSUE TITLE
hi, i want to try to run the experiment result but error, how do i handle the configuration part?

### ISSUE THREAD

**Issue by AARNH** [BioMedIA-MBZUAI/contrastive-echo#2]
`Epoch 0    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/136 0:00:00 • -:--:-- 0.00it/s  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ariqoh\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\ariqoh\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\ariqoh\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ariqoh\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\ariqoh\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 264, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\ariqoh\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 234, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ujicoba\\exs\\logs\\runs\\2023-06-09\\23-05-25\\run.py'`

**Comment by sjoshi804** [comment]
Running into the same error

**Comment by meltag12** [comment]
Apologies for the delayed response. Please use the updated [echonet_simclr.yaml](https://github.com/BioMedIA-MBZUAI/contrastive-echo/blob/main/configs/experiment/echonet_simclr.yaml). In addition, make sure that you have write permissions for your logs directory. Hope this fixes the issue.
